/* Arcade Ledger: neo-brutalist editorial game UI; cream paper, charcoal ink, burnt orange action, green growth. Mobile-first expansion with achievements, offline economy and tactile audio. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Award, Banknote, Bell, ChartNoAxesCombined, ChevronRight, CircleHelp, Clock3, Factory, Lightbulb, LockKeyhole, RotateCcw, Sparkles, Store, TrendingUp, Volume2, VolumeX, WalletCards, Zap } from "lucide-react";

type Asset = { name: string; detail: string; basePrice: number; income: number; icon: string; owned: number };
type GameState = { money: number; clickPower: number; clickUpgradeLevel: number; autoIncome: number; assets: Asset[]; events: string[]; lifetime: number; clicks: number; lastSeen: number; offlineReward: number };
const initialAssets: Asset[] = [
  { name: "عامل مساعد", detail: "ينقر بدلًا عنك", basePrice: 10, income: 1, icon: "01", owned: 0 }, { name: "مشروع صغير", detail: "أول فرع يفتح الدفتر", basePrice: 100, income: 5, icon: "02", owned: 0 }, { name: "مشروع متوسط", detail: "فريق مبيعات مصغّر", basePrice: 1000, income: 10, icon: "03", owned: 0 }, { name: "مشروع كبير", detail: "حساب مؤسسي جديد", basePrice: 10000, income: 20, icon: "04", owned: 0 }, { name: "مزرعة", detail: "تورّد السلع للشبكة", basePrice: 100000, income: 25, icon: "05", owned: 0 }, { name: "مصنع صغير", detail: "يصنع الربح على مدار الساعة", basePrice: 1000000, income: 40, icon: "06", owned: 0 }, { name: "مصنع الدهانات", detail: "علامة على كل جدار", basePrice: 10000000, income: 80, icon: "07", owned: 0 }, { name: "المصنع", detail: "خط إنتاج لا ينام", basePrice: 100000000, income: 110, icon: "08", owned: 0 }, { name: "شركة المراقبة", detail: "تراقب الفرص قبل الجميع", basePrice: 1000000000, income: 160, icon: "09", owned: 0 }, { name: "شبكة المتاجر", detail: "الإمبراطورية تبدأ هنا", basePrice: 10000000000, income: 250, icon: "10", owned: 0 },
];
const initialState: GameState = { money: 0, clickPower: 1, clickUpgradeLevel: 0, autoIncome: 0, assets: initialAssets, events: ["افتح الدفتر — أول نقرة لك تنتظر."], lifetime: 0, clicks: 0, lastSeen: Date.now(), offlineReward: 0 };
const clickUpgrades = [{ name: "قلم أسرع", detail: "+1 لكل نقرة", price: 10, add: 1 }, { name: "آلة حاسبة", detail: "+2 لكل نقرة", price: 100, add: 2 }, { name: "قسم المبيعات", detail: "+5 لكل نقرة", price: 1000, add: 5 }];
const stages = [{ name: "الفكرة", target: 0, note: "رأس المال يبدأ من نقرة" }, { name: "المشروع", target: 100, note: "أول 100$ في الدفتر" }, { name: "الشركة", target: 1000, note: "أول 1,000$ — الآن بدأ العمل" }, { name: "الإمبراطورية", target: 10000, note: "10,000$ — كل شيء قابل للتوسع" }];
const money = (n: number) => n.toLocaleString("en-US", { maximumFractionDigits: 0 });
const priceFor = (asset: Asset) => asset.basePrice * Math.pow(2, asset.owned);
const loadGame = (): GameState => { try { const saved = localStorage.getItem("business-clicker-save"); if (!saved) return initialState; const parsed = { ...initialState, ...JSON.parse(saved) } as GameState; const elapsed = Math.max(0, Math.floor((Date.now() - (parsed.lastSeen || Date.now())) / 1000)); const payableSeconds = Math.min(elapsed, 8 * 60 * 60); const reward = parsed.autoIncome * payableSeconds; return { ...parsed, money: parsed.money + reward, lifetime: parsed.lifetime + reward, lastSeen: Date.now(), offlineReward: reward, events: reward ? [`عاد الدخل الغائب: +${money(reward)}$`, ...parsed.events].slice(0, 6) : parsed.events }; } catch { return initialState; } };
const playTone = (muted: boolean, kind: "click" | "buy" | "milestone") => { if (muted || typeof window === "undefined") return; const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const ctx = new AudioContextClass(); const now = ctx.currentTime; const notes = kind === "buy" ? [392, 523, 659] : kind === "milestone" ? [330, 440, 660, 880] : [220, 330]; notes.forEach((frequency, i) => { const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.type = kind === "click" ? "square" : "triangle"; osc.frequency.value = frequency; gain.gain.setValueAtTime(0.0001, now + i * 0.055); gain.gain.exponentialRampToValueAtTime(kind === "click" ? 0.035 : 0.06, now + i * 0.055 + 0.01); gain.gain.exponentialRampToValueAtTime(0.0001, now + i * 0.055 + 0.11); osc.connect(gain).connect(ctx.destination); osc.start(now + i * 0.055); osc.stop(now + i * 0.055 + 0.12); }); window.setTimeout(() => ctx.close(), 600); };

export default function Home() {
  const [game, setGame] = useState<GameState>(loadGame); const [pulse, setPulse] = useState(false); const [floating, setFloating] = useState<number[]>([]); const [showHelp, setShowHelp] = useState(false); const [muted, setMuted] = useState(() => localStorage.getItem("business-clicker-muted") === "true"); const [showAchievements, setShowAchievements] = useState(false); const [offlineVisible, setOfflineVisible] = useState(() => loadGame().offlineReward > 0);
  const affordable = useMemo(() => game.assets.filter((a) => game.money >= priceFor(a)).length, [game.money, game.assets]);
  const currentStage = [...stages].reverse().find((stage) => game.lifetime >= stage.target) || stages[0]; const nextStage = stages.find((stage) => stage.target > currentStage.target); const stageProgress = nextStage ? Math.min(100, ((game.lifetime - currentStage.target) / (nextStage.target - currentStage.target)) * 100) : 100;
  const achievements = useMemo(() => [{ title: "أول 100$", detail: "اجمع أول مئة دولار", done: game.lifetime >= 100, icon: "01" }, { title: "أول 1,000$", detail: "حوّل النقرة إلى مشروع", done: game.lifetime >= 1000, icon: "02" }, { title: "أول أصل", detail: "اشترِ أول مصدر دخل", done: game.assets.some((a) => a.owned > 0), icon: "03" }, { title: "امتلاك أول مصنع", detail: "اشترِ المصنع لأول مرة", done: game.assets[7]?.owned > 0, icon: "04" }, { title: "دخل مؤثر", detail: "بلّغ 100$ دخلًا في الثانية", done: game.autoIncome >= 100, icon: "05" }], [game]);
  useEffect(() => { localStorage.setItem("business-clicker-save", JSON.stringify({ ...game, lastSeen: Date.now(), offlineReward: 0 })); }, [game]);
  useEffect(() => { const timer = window.setInterval(() => setGame((g) => g.autoIncome ? { ...g, money: g.money + g.autoIncome, lifetime: g.lifetime + g.autoIncome, lastSeen: Date.now() } : { ...g, lastSeen: Date.now() }), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { localStorage.setItem("business-clicker-muted", String(muted)); }, [muted]);
  const click = () => { playTone(muted, "click"); setGame((g) => ({ ...g, money: g.money + g.clickPower, lifetime: g.lifetime + g.clickPower, clicks: g.clicks + 1, events: [`نقرة صافية +${money(g.clickPower)}$`, ...g.events].slice(0, 6) })); setPulse(true); setFloating((f) => [...f, Date.now()]); window.setTimeout(() => setPulse(false), 150); };
  const buyClickUpgrade = (u: typeof clickUpgrades[number], i: number) => { if (game.money < u.price || game.clickUpgradeLevel !== i) return; playTone(muted, "buy"); setGame((g) => ({ ...g, money: g.money - u.price, clickPower: g.clickPower + u.add, clickUpgradeLevel: i + 1, events: [`ترقية النقرة: ${u.name}`, ...g.events].slice(0, 6) })); };
  const buyAsset = (index: number) => { const asset = game.assets[index]; const price = priceFor(asset); if (game.money < price) return; playTone(muted, "buy"); setGame((g) => { const assets = g.assets.map((a, i) => i === index ? { ...a, owned: a.owned + 1 } : a); return { ...g, money: g.money - price, autoIncome: g.autoIncome + asset.income, assets, events: [`تم شراء ${asset.name} — دخل +${asset.income}$/ث`, ...g.events].slice(0, 6) }; }); };
  const reset = () => { if (window.confirm("هل تريد بدء دفتر جديد؟ سيتم حذف التقدم المحلي.")) { playTone(muted, "click"); setGame({ ...initialState, lastSeen: Date.now() }); setOfflineVisible(false); } };
  return <main className="ledger-shell" dir="rtl"><header className="topbar"><div className="brand"><img src="/manus-storage/business-clicker-mark_87ac56c0.png" alt="" className="brand-mark" /><div><div className="brand-word">BUSINESS</div><div className="brand-sub">CLICKER / دفتر النمو</div></div></div><div className="top-actions"><span className="save-state"><span className="status-dot" /> محفوظ محليًا</span><button className="icon-button" aria-label={muted ? "تشغيل الصوت" : "كتم الصوت"} onClick={() => setMuted(!muted)}>{muted ? <VolumeX size={19} /> : <Volume2 size={19} />}</button><button className="icon-button" aria-label="الإنجازات" onClick={() => setShowAchievements(!showAchievements)}><Award size={19} /></button><button className="icon-button" aria-label="مساعدة" onClick={() => setShowHelp(!showHelp)}><CircleHelp size={19} /></button><button className="icon-button" aria-label="إعادة التعيين" onClick={reset}><RotateCcw size={17} /></button></div></header>{(showHelp || showAchievements) && <div className="utility-drawer">{showHelp && <div className="help-note"><b>كيف تلعب؟</b> انقر على ختم الصفقة، ثم اشترِ أصولًا تمنحك دخلًا تلقائيًا. يتم احتساب أرباحك أثناء غيابك حتى 8 ساعات.</div>}{showAchievements && <div className="achievement-drawer"><div><span className="panel-kicker orange">لوحة الإنجازات</span><h3>علامات على الطريق</h3></div><div className="achievement-grid">{achievements.map((item) => <div className={`achievement-card ${item.done ? "done" : ""}`} key={item.title}><span>{item.done ? "✓" : item.icon}</span><div><b>{item.title}</b><small>{item.detail}</small></div></div>)}</div></div>}</div>}{offlineVisible && game.offlineReward > 0 && <div className="offline-banner"><div className="offline-icon"><Clock3 size={19} /></div><div><b>عاد الدفتر للعمل.</b><span>ربحك أثناء الغياب: <strong>+{money(game.offlineReward)}$</strong></span></div><button onClick={() => setOfflineVisible(false)}>استلام</button></div>}
  <section className="dashboard-grid"><aside className="ledger-panel paper-panel"><div className="panel-kicker"><span className="ledger-tab">سجل العمليات</span> / 001</div><h2>دفتر<br /><em>النشاط</em></h2><div className="ledger-rule" />{game.events.map((event, i) => <div className="event-row" key={`${event}-${i}`}><span className="event-index">{String(i + 1).padStart(2, "0")}</span><span>{event}</span></div>)}<div className="ledger-bottom"><TrendingUp size={17} /><span>الدخل الجاري</span><strong>{money(game.autoIncome)}$<small> / ثانية</small></strong></div></aside>
  <section className="play-area"><div className="eyebrow"><span>مرحلة: <b>{currentStage.name}</b></span><span className="live-pill"><span className="status-dot green" /> اقتصاد مباشر</span></div><div className="hero-copy"><h1>حوّل النقرة<br /><span>إلى شركة.</span></h1><p>ابدأ من الصفر. ابنِ الأصل التالي. دع الأرقام تتكلم.</p></div><div className="click-stage"><div className="stage-caption"><span><span className="mini-stamp">DEAL</span> الرصيد الحالي</span><span className="hash">#CLICK-TO-GROW</span></div><div className="money-display">{money(game.money)}<span>$</span></div><button className={`deal-button ${pulse ? "pressed" : ""}`} onClick={click}><span className="deal-seal">DEAL<br /><i>×</i><br />CLOSED</span><img src="/manus-storage/business-clicker-mark_87ac56c0.png" alt="" /><span>اضغط<br /><b>لتحصيل الصفقة</b></span><small>+{money(game.clickPower)}$ / نقرة</small></button>{floating.map((id) => <span className="float-cash" key={id}>+{money(game.clickPower)}$</span>)}</div><div className="growth-strip"><span>مؤشر الحركة</span><i style={{ width: `${Math.max(22, stageProgress)}%` }} /><b>{nextStage ? `الهدف التالي: ${nextStage.name}` : "الإمبراطورية مكتملة"}</b></div><div className="stage-card"><div className="stage-card-icon"><ChartNoAxesCombined size={20} /></div><div><span>المرحلة الحالية</span><b>{currentStage.name}</b><small>{nextStage ? `${nextStage.note} · ${Math.round(stageProgress)}%` : "كل الأهداف الكبرى تحققت"}</small></div><div className="stage-target">{nextStage ? `${money(nextStage.target)}$` : "MAX"}</div></div><div className="quick-stats"><div><Banknote size={18} /><span>إجمالي الأرباح</span><b>{money(game.lifetime)}$</b></div><div><Zap size={18} /><span>قوة النقرة</span><b>+{money(game.clickPower)}$</b></div><div><Store size={18} /><span>الأصول المملوكة</span><b>{game.assets.reduce((a, x) => a + x.owned, 0)}</b></div></div></section>
  <aside className="shop-panel"><div className="shop-header"><div><div className="panel-kicker orange">قسم المشتريات</div><h2>كبّر<br /><em>اللعبة</em></h2></div><div className="available-count">{affordable}<small> متاح</small></div></div><div className="shop-scroll"><div className="upgrade-block"><div className="section-label"><span><span className="ledger-tab">ترقية</span> النقر</span><span>مرة واحدة</span></div>{clickUpgrades.map((u, i) => <button className={`upgrade-row ${game.clickUpgradeLevel > i ? "owned-row" : ""} ${game.clickUpgradeLevel !== i ? "locked" : ""}`} key={u.name} onClick={() => buyClickUpgrade(u, i)}><span className="row-icon"><Sparkles size={15} /></span><span className="row-copy"><b>{u.name}</b><small>{game.clickUpgradeLevel > i ? "تم الاستحواذ" : u.detail}</small></span><strong>{game.clickUpgradeLevel > i ? "✓" : `${money(u.price)}$`}</strong><ChevronRight size={15} /></button>)}</div><div className="upgrade-block assets"><div className="section-label"><span><span className="ledger-tab">أصول</span> الدخل التلقائي</span><span>يتضاعف السعر</span></div>{game.assets.map((asset, i) => <button className={`asset-row ${game.money >= priceFor(asset) ? "ready" : ""}`} key={asset.name} onClick={() => buyAsset(i)}><span className="asset-no">{asset.icon}</span><span className="row-copy"><b>{asset.name}</b><small>+{asset.income}$/ث · {asset.owned} مملوك</small></span><strong>{money(priceFor(asset))}$</strong><ArrowUpRight size={15} /></button>)}</div></div></aside></section><footer className="footer-bar"><span><WalletCards size={15} /> Business Clicker / نسخة ويب</span><span><Bell size={13} /> {muted ? "الصوت مكتوم" : "الصوت مفعّل"}</span><span>الإصدار 1.1</span></footer></main>;
}
