/* Reference-match mobile game shell: portrait luxury estate, glass finance card, gold tap zone, action rails, bottom navigation. */
import { useEffect, useMemo, useState } from "react";
import { Award, BarChart3, BriefcaseBusiness, ChevronRight, CircleHelp, Gift, Home as HomeIcon, Menu, RotateCcw, ShoppingCart, Sparkles, TrendingUp, Volume2, VolumeX, WalletCards, Zap, Clock3 } from "lucide-react";

type Asset={name:string;detail:string;basePrice:number;income:number;icon:string;owned:number};
type GameState={money:number;clickPower:number;clickUpgradeLevel:number;autoIncome:number;assets:Asset[];events:string[];lifetime:number;clicks:number;lastSeen:number;offlineReward:number};
const initialAssets:Asset[]=[{name:"عامل مساعد",detail:"ينقر بدلًا عنك",basePrice:10,income:1,icon:"01",owned:0},{name:"مشروع صغير",detail:"أول فرع يفتح الدفتر",basePrice:100,income:5,icon:"02",owned:0},{name:"مشروع متوسط",detail:"فريق مبيعات مصغّر",basePrice:1000,income:10,icon:"03",owned:0},{name:"مشروع كبير",detail:"حساب مؤسسي جديد",basePrice:10000,income:20,icon:"04",owned:0},{name:"مزرعة",detail:"تورّد السلع للشبكة",basePrice:100000,income:25,icon:"05",owned:0},{name:"مصنع صغير",detail:"يصنع الربح",basePrice:1000000,income:40,icon:"06",owned:0},{name:"مصنع الدهانات",detail:"علامة على كل جدار",basePrice:10000000,income:80,icon:"07",owned:0},{name:"المصنع",detail:"خط إنتاج لا ينام",basePrice:100000000,income:110,icon:"08",owned:0},{name:"شركة المراقبة",detail:"تراقب الفرص",basePrice:1000000000,income:160,icon:"09",owned:0},{name:"شبكة المتاجر",detail:"الإمبراطورية تبدأ",basePrice:10000000000,income:250,icon:"10",owned:0}];
const initialState:GameState={money:0,clickPower:1,clickUpgradeLevel:0,autoIncome:0,assets:initialAssets,events:["افتح الدفتر — الصفقة الأولى تنتظر."],lifetime:0,clicks:0,lastSeen:Date.now(),offlineReward:0};
const upgrades=[{name:"قلم أسرع",detail:"+1 لكل نقرة",price:10,add:1},{name:"آلة حاسبة",detail:"+2 لكل نقرة",price:100,add:2},{name:"قسم المبيعات",detail:"+5 لكل نقرة",price:1000,add:5}];
const money=(n:number)=>n.toLocaleString("en-US",{maximumFractionDigits:0}); const priceFor=(a:Asset)=>a.basePrice*Math.pow(2,a.owned);
const loadGame=():GameState=>{try{const raw=localStorage.getItem("business-clicker-save");if(!raw)return initialState;const g={...initialState,...JSON.parse(raw)} as GameState;const seconds=Math.min(8*60*60,Math.max(0,Math.floor((Date.now()-(g.lastSeen||Date.now()))/1000)));const reward=g.autoIncome*seconds;return {...g,money:g.money+reward,lifetime:g.lifetime+reward,lastSeen:Date.now(),offlineReward:reward,events:reward?[`عاد الدخل أثناء الغياب: +${money(reward)}$`,...g.events].slice(0,6):g.events};}catch{return initialState;}};
const tone=(muted:boolean,kind:"tap"|"buy")=>{if(muted)return;const C=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type=kind==="tap"?"sine":"triangle";o.frequency.value=kind==="tap"?260:520;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.12);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.13);setTimeout(()=>c.close(),400);};
export default function Home(){const [game,setGame]=useState<GameState>(loadGame);const [muted,setMuted]=useState(()=>localStorage.getItem("business-clicker-muted")==="true");const [tab,setTab]=useState("clicker");const [pulse,setPulse]=useState(false);const [float,setFloat]=useState<number[]>([]);const [offline,setOffline]=useState(()=>loadGame().offlineReward>0);const [showAchievements,setShowAchievements]=useState(false);const nextAsset=game.assets.find(a=>game.money<priceFor(a));const allOwned=game.assets.reduce((s,a)=>s+a.owned,0);const achievements=useMemo(()=>[{title:"أول 100$",done:game.lifetime>=100},{title:"أول 1,000$",done:game.lifetime>=1000},{title:"أول أصل",done:allOwned>0},{title:"أول مصنع",done:game.assets[7]?.owned>0}], [game,allOwned]);
useEffect(()=>{localStorage.setItem("business-clicker-save",JSON.stringify({...game,lastSeen:Date.now(),offlineReward:0}));},[game]);useEffect(()=>{const id=setInterval(()=>setGame(g=>({...g,money:g.money+g.autoIncome,lifetime:g.lifetime+g.autoIncome,lastSeen:Date.now()})),1000);return()=>clearInterval(id);},[]);useEffect(()=>localStorage.setItem("business-clicker-muted",String(muted)),[muted]);
const tap=()=>{tone(muted,"tap");setGame(g=>({...g,money:g.money+g.clickPower,lifetime:g.lifetime+g.clickPower,clicks:g.clicks+1,events:[`نقرة +${money(g.clickPower)}$`,...g.events].slice(0,6)}));setPulse(true);setFloat(f=>[...f,Date.now()]);setTimeout(()=>setPulse(false),140);};
const buyUpgrade=(u:typeof upgrades[number],i:number)=>{if(game.money<u.price||game.clickUpgradeLevel!==i)return;tone(muted,"buy");setGame(g=>({...g,money:g.money-u.price,clickPower:g.clickPower+u.add,clickUpgradeLevel:i+1,events:[`ترقية ${u.name}`,...g.events].slice(0,6)}));};
const buyAsset=(i:number)=>{const a=game.assets[i],p=priceFor(a);if(game.money<p)return;tone(muted,"buy");setGame(g=>({...g,money:g.money-p,autoIncome:g.autoIncome+a.income,assets:g.assets.map((x,j)=>j===i?{...x,owned:x.owned+1}:x),events:[`تم شراء ${a.name}`,...g.events].slice(0,6)}));};
const reset=()=>{if(confirm("بدء لعبة جديدة؟")){setGame({...initialState,lastSeen:Date.now()});setOffline(false);}};
return <main className="mobile-game"><div className="game-bg"/><div className="game-scrim"/><section className="game-app"><header className="profile-bar"><div className="avatar"><span>BC</span><b>8</b></div><div className="profile-copy"><strong>{money(game.lifetime)}</strong><span>المستثمر · المستوى {game.lifetime>=1000?3:game.lifetime>=100?2:1}</span><i><em style={{width:`${Math.min(100,(game.lifetime%1000)/10)}%`}}/></i></div><button className="rank-chip" onClick={()=>setShowAchievements(true)}><Award size={18}/><b>{achievements.filter(a=>a.done).length}</b><small>إنجازات</small><ChevronRight size={16}/></button></header><div className="game-head"><button className="round-control" onClick={()=>setTab("business")}><Menu size={20}/></button><span><span className="online-dot"/> GLOBEX <b>PLATINUM</b></span><div><span>•••</span><button onClick={()=>setMuted(!muted)} aria-label="الصوت">{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div></div>{offline&&game.offlineReward>0&&<div className="offline-pop"><Clock3 size={18}/><span><b>أثناء غيابك</b><small>دخل تلقائي +{money(game.offlineReward)}$</small></span><button onClick={()=>setOffline(false)}>استلام</button></div>}
<div className="balance-card"><div className="card-top"><span>رصيد الأعمال</span><span>#{String(game.clicks+1).padStart(4,"0")}</span></div><strong>$ {money(game.money)}</strong><small>الرصيد الإجمالي</small><div className="card-bottom"><span>دخل تلقائي <b>+{money(game.autoIncome)}$ / ث</b></span><span className="card-dots">● ●</span></div></div>
{tab==="clicker"&&<><div className="tap-zone"><button className={`gold-tap ${pulse?"tap-active":""}`} onClick={tap} aria-label="اضغط لتحصيل المال"><span className="tap-ring"/><span className="tap-hand">☝</span><small>اضغط للتحصيل</small></button>{float.map(id=><b className="float-number" key={id}>+{money(game.clickPower)}$</b>)}</div><div className="tap-reward"><span><WalletCards size={19}/></span><div><b>اضغط للربح!</b><small>كل نقرة تضيف إلى إمبراطوريتك</small></div><strong>+{money(game.clickPower)}$<small>لكل نقرة</small></strong></div><div className="quick-actions"><button className="upgrade-action" onClick={()=>setTab("shop")}><Zap size={22}/><span><b>ترقية النقرة</b><small>المستوى {game.clickUpgradeLevel+1} · +{money(upgrades[Math.min(game.clickUpgradeLevel,2)].add)}$</small></span><strong>{money(upgrades[Math.min(game.clickUpgradeLevel,2)].price)}$</strong></button><button className="booster-action" onClick={()=>setShowAchievements(true)}><Sparkles size={22}/><span><b>المكافآت</b><small>{achievements.filter(a=>a.done).length}/4 إنجازات</small></span><ChevronRight/></button></div></>}
{tab==="shop"&&<div className="mobile-panel"><div className="panel-title"><span>متجر الأعمال</span><b>{game.assets.filter(a=>game.money>=priceFor(a)).length} متاح</b></div>{upgrades.map((u,i)=><button className="mobile-row" key={u.name} onClick={()=>buyUpgrade(u,i)}><span className="row-badge"><Zap size={14}/></span><span><b>{u.name}</b><small>{game.clickUpgradeLevel>i?"تم الشراء":u.detail}</small></span><strong>{game.clickUpgradeLevel>i?"✓":money(u.price)+"$"}</strong></button>)}{game.assets.slice(0,6).map((a,i)=><button className="mobile-row" key={a.name} onClick={()=>buyAsset(i)}><span className="asset-number">{a.icon}</span><span><b>{a.name}</b><small>+{a.income}$/ث · {a.owned} مملوك</small></span><strong>{money(priceFor(a))}$</strong></button>)}</div>}
{tab==="business"&&<div className="mobile-panel activity-panel"><div className="panel-title"><span>سجل الأعمال</span><b>{money(game.autoIncome)}$ / ثانية</b></div>{game.events.map((e,i)=><div className="activity-row" key={`${e}${i}`}><span>0{i+1}</span>{e}</div>)}</div>}
<nav className="bottom-nav"><button onClick={()=>setTab("invest")} className={tab==="invest"?"active":""}><TrendingUp/><span>استثمار</span></button><button onClick={()=>setTab("business")} className={tab==="business"?"active":""}><BriefcaseBusiness/><span>أعمال</span></button><button onClick={()=>setTab("clicker")} className={`main-nav ${tab==="clicker"?"active":""}`}><span><HomeIcon/></span><label>نقر</label></button><button onClick={()=>setTab("shop")} className={tab==="shop"?"active":""}><ShoppingCart/><span>المتجر</span></button><button onClick={()=>setShowAchievements(true)}><Gift/><span>جوائز</span></button></nav></section>{showAchievements&&<div className="achievement-modal" onClick={()=>setShowAchievements(false)}><div className="achievement-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-grab"/><div className="sheet-head"><div><span>مسار المستثمر</span><h2>إنجازاتك</h2></div><button onClick={()=>setShowAchievements(false)}>×</button></div>{achievements.map((a,i)=><div className={`achievement-line ${a.done?"done":""}`} key={a.title}><span>{a.done?"✓":`0${i+1}`}</span><div><b>{a.title}</b><small>{a.done?"تم فتح الإنجاز":"واصل اللعب لفتح هذا الإنجاز"}</small></div><Award size={18}/></div>)}<button className="reset-link" onClick={reset}><RotateCcw size={14}/> إعادة اللعبة</button></div></div>}</main>}
